// Cloudflare Email Worker: wfweb@k1fm.us → GitHub issue in adecarolis/wfweb.
//
// Bound to the address in the dashboard: Email Routing → Routing rules →
// custom address → action "Send to a Worker". No HTTP routes.
//
// Small text attachments (debug logs) are inlined into the issue body;
// anything else is committed to the `support-attachments` branch and linked.
// If issue creation fails the handler throws, so Cloudflare temp-fails the
// message and the sender's server retries later — mail is never dropped.

import PostalMime from "postal-mime";

const REPO = "adecarolis/wfweb";
const API = `https://api.github.com/repos/${REPO}`;
const ATTACH_BRANCH = "support-attachments";
const MAX_INLINE = 50_000; // bytes of a text attachment inlined into the issue
const MAX_BODY = 60_000;   // GitHub caps issue bodies at 65536 chars

export default {
  async email(message, env, ctx) {
    if (isAutoGenerated(message)) return;

    // Forward the human copy first so the mail reaches Alain even if GitHub
    // is down. A GitHub failure below makes the sender retry the whole
    // message, which can duplicate this forward — acceptable.
    if (env.FORWARD_TO) {
      try {
        await message.forward(env.FORWARD_TO);
      } catch {}
    }

    const mail = await PostalMime.parse(message.raw);
    const stamp = new Date().toISOString().replace(/[:.]/g, "-");

    const sections = [
      `**From:** ${escapeMd(mail.from?.name || "")} \`${message.from}\``,
      `**Subject:** ${escapeMd(mail.subject || "(no subject)")}`,
      `**Received:** ${new Date().toISOString()}`,
      "",
      "---",
      "",
      textBody(mail) || "_(empty body)_",
    ];

    for (const att of mail.attachments || []) {
      const name = att.filename || "attachment";
      const bytes = toUint8(att.content);
      if (isTextAttachment(att, name) && bytes.length <= MAX_INLINE) {
        sections.push(
          "",
          `<details><summary>📎 ${escapeMd(name)} (${bytes.length} bytes)</summary>`,
          "",
          "```",
          new TextDecoder().decode(bytes).replaceAll("```", "`​``"),
          "```",
          "",
          "</details>"
        );
      } else {
        const path = `${stamp}/${name.replace(/[^\w.\-]/g, "_")}`;
        try {
          await commitAttachment(env, path, bytes, message.from);
          sections.push(
            "",
            `📎 [\`${name}\`](https://github.com/${REPO}/blob/${ATTACH_BRANCH}/${path}) (${bytes.length} bytes)`
          );
        } catch (e) {
          sections.push("", `📎 \`${name}\` (${bytes.length} bytes) — upload failed: ${e.message}`);
        }
      }
    }

    let body = sections.join("\n");
    if (body.length > MAX_BODY) body = body.slice(0, MAX_BODY) + "\n\n_(truncated)_";

    const res = await fetch(`${API}/issues`, {
      method: "POST",
      headers: ghHeaders(env),
      body: JSON.stringify({
        title: `[support] ${mail.subject || `mail from ${message.from}`}`.slice(0, 250),
        body,
        labels: ["support-inbox"],
      }),
    });
    if (!res.ok) {
      throw new Error(`GitHub issue creation failed: ${res.status} ${await res.text()}`);
    }
  },
};

// Bounces and autoresponders must not open issues (or mail-loop with them).
function isAutoGenerated(message) {
  const auto = message.headers.get("auto-submitted");
  if (auto && auto.toLowerCase() !== "no") return true;
  const from = message.from.toLowerCase();
  return from.startsWith("mailer-daemon@") || from.startsWith("postmaster@");
}

function textBody(mail) {
  if (mail.text?.trim()) return mail.text.trim();
  if (mail.html) {
    return mail.html
      .replace(/<style[\s\S]*?<\/style>/gi, "")
      .replace(/<[^>]+>/g, " ")
      .replace(/&nbsp;/g, " ")
      .replace(/\s+\n/g, "\n")
      .replace(/[ \t]{2,}/g, " ")
      .trim();
  }
  return "";
}

function isTextAttachment(att, name) {
  return (
    (att.mimeType || "").startsWith("text/") ||
    /\.(log|txt|json|md)$/i.test(name)
  );
}

async function commitAttachment(env, path, bytes, sender) {
  const res = await fetch(`${API}/contents/${encodeURI(path)}`, {
    method: "PUT",
    headers: ghHeaders(env),
    body: JSON.stringify({
      message: `support attachment from ${sender}`,
      branch: ATTACH_BRANCH,
      content: base64(bytes),
    }),
  });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
}

function ghHeaders(env) {
  return {
    authorization: `Bearer ${env.GITHUB_TOKEN}`,
    accept: "application/vnd.github+json",
    "user-agent": "wfweb-support-inbox",
    "content-type": "application/json",
  };
}

function toUint8(content) {
  if (typeof content === "string") return new TextEncoder().encode(content);
  return content instanceof Uint8Array ? content : new Uint8Array(content);
}

function base64(bytes) {
  let bin = "";
  for (let i = 0; i < bytes.length; i += 0x8000) {
    bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return btoa(bin);
}

function escapeMd(s) {
  return s.replace(/([\\`*_[\]<>])/g, "\\$1");
}
